apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ experiment_name }}
  namespace: {{ namespace }}
spec:
  hard:
    requests.cpu: {{ cpu_requests }}
    requests.memory: {{ mem_requests }}
    limits.cpu: {{ cpu_limits }}
    limits.memory: {{ mem_limits }}
