apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ experiment_name }}
  namespace: {{ namespace }}
spec:
  podSelector:
    matchLabels:
      {{ lable_name }}: {{ label_value }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: "true"